In [124]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import re
warnings.filterwarnings('ignore')

In [125]:
df = pd.read_excel("spam.xlsx")

In [126]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: object(1), str(4)
memory usage: 239.9+ KB

In [128]:
df = df.drop( columns= ['Unnamed: 2',	'Unnamed: 3'	,'Unnamed: 4'])

In [129]:
df= df.rename( columns={'v1':'label', 'v2':'text'})

In [130]:
df['text']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will �_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: text, Length: 5572, dtype: object

In [131]:
df['text']= df['text'].astype(str)
df_clean = df.copy()
df_clean['text'] = df['text'].str.lower()

In [132]:
df_clean['text'].dtype

In [133]:
df_clean['text'].dropna(inplace= True)

In [134]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to C:\Users\Syam
[nltk_data]     Sundar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Syam
[nltk_data]     Sundar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Syam
[nltk_data]     Sundar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [135]:
stop_words = set( stopwords.words('english'))

In [136]:
def remove_puc(msg):
    clean_text = re.sub(r'[^\w\s]', '', msg)
    clean_text
    return clean_text

In [137]:
 df_clean['text'] = df_clean['text'].apply(remove_puc)

In [138]:
from nltk.tokenize import word_tokenize

lemmetizer = WordNetLemmatizer()
df_clean['text']  = df_clean['text'].apply(word_tokenize)

In [139]:
#  Remove stop words 
df_clean['text'] = df_clean['text'].apply( lambda val : [words for  words in val  if words not in stop_words] )
df_clean['text'] = df_clean['text'].apply( lambda val: [lemmetizer.lemmatize(words) for words in val] )

In [144]:
df_clean['text'] = df_clean['text'].apply( lambda val: " ".join([words for words in val]) )

In [145]:
df_clean['text']

0       go jurong point crazy available bugis n great ...
1                                 ok lar joking wif u oni
2       free entry 2 wkly comp win fa cup final tkts 2...
3                     u dun say early hor u c already say
4                nah dont think go usf life around though
                              ...
5567    2nd time tried 2 contact u u 750 pound prize 2...
5568                          _ b going esplanade fr home
5569                           pity mood soany suggestion
5570    guy bitching acted like id interested buying s...
5571                                       rofl true name
Name: text, Length: 5572, dtype: str

In [149]:
df_clean['label'] = df_clean['label'].map({ 'ham':0, 'spam':1})

In [152]:
label = df_clean['label']

In [168]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report , f1_score, precision_score, accuracy_score, confusion_matrix

In [153]:
vectorizer = TfidfVectorizer(ngram_range=(1,2) )
X = vectorizer.fit_transform(df['text'])
model = LogisticRegression()

X_train, X_test, y_train, y_test =  train_test_split(X, label , test_size= 0.3 , random_state= 67)

In [155]:
model.fit(X_train, y_train)

LogisticRegression()

In [157]:
y_predict =  model.predict(X_test )

In [158]:
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [164]:
precision = precision_score(y_test, y_predict )
accuracy = accuracy_score(y_test, y_predict )
precision
accuracy

0.9300239234449761

In [167]:
report = classification_report( y_test, y_predict )
print(report)

              precision    recall  f1-score   support

           0       0.92      1.00      0.96      1439
           1       1.00      0.50      0.66       233

    accuracy                           0.93      1672
   macro avg       0.96      0.75      0.81      1672
weighted avg       0.94      0.93      0.92      1672

In [169]:
confu = confusion_matrix(y_test, y_predict)
confu

array([[1439,    0],
       [ 117,  116]])

In [170]:
df_clean[df_clean['label'] ==1]

      label                                               text
2         1  free entry 2 wkly comp win fa cup final tkts 2...
5         1  freemsg hey darling 3 week word back id like f...
8         1  winner valued network customer selected receiv...
9         1  mobile 11 month u r entitled update latest col...
11        1  six chance win cash 100 20000 pound txt csh11 ...
...     ...                                                ...
5537      1  want explicit sex 30 sec ring 02073162414 cost...
5540      1  asked 3mobile 0870 chatlines inclu free min in...
5547      1  contract mobile 11 mnths latest motorola nokia...
5566      1  reminder o2 get 250 pound free call credit det...
5567      1  2nd time tried 2 contact u u 750 pound prize 2...

[747 rows x 2 columns]

In [171]:
df[df['label'] =='spam']

     label                                               text
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...
11    spam  SIX chances to win CASH! From 100 to 20,000 po...
...    ...                                                ...
5537  spam  Want explicit SEX in 30 secs? Ring 02073162414...
5540  spam  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547  spam  Had your contract mobile 11 Mnths? Latest Moto...
5566  spam  REMINDER FROM O2: To get 2.50 pounds free call...
5567  spam  This is the 2nd time we have tried 2 contact u...

[747 rows x 2 columns]

In [175]:
y_prob = model.predict_proba(X_test)[:, 1]
threshold = 0.2
y_pred_new = (y_prob >= threshold).astype(int)

print(f"\nThreshold: {threshold}")
print(classification_report(y_test, y_pred_new))
print( confusion_matrix(y_test, y_pred_new))

Threshold: 0.2
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1439
           1       0.97      0.86      0.91       233

    accuracy                           0.98      1672
   macro avg       0.97      0.93      0.95      1672
weighted avg       0.98      0.98      0.98      1672

[[1432    7]
 [  33  200]]

In [179]:
import pickle as pkl

#  Data_x , Data_y , tfidf , 


pkl.dump(vectorizer , open('tfidf.pkl', 'wb') )
pkl.dump(model , open('model.pkl', 'wb') )